Model: MobileNetV2
Transforms:
- ResizeByShort:
    interp: LINEAR
    max_size: -1
    short_size: 256
- CenterCrop:
    crop_size: 224
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.0
    - 0.0
    - 0.0
    min_val:
    - 0
    - 0
    - 0
    std:
    - 1.0
    - 1.0
    - 1.0
_Attributes:
  eval_metrics:
    acc1: 0.945652186870575
  fixed_input_shape:
  - -1
  - 3
  - -1
  - -1
  labels:
  - baihe
  - dangshen
  - gouqi
  - huaihua
  - jinyinhua
  model_type: classifier
  num_classes: 5
_init_params:
  num_classes: 5
completed_epochs: 0
status: Infer
version: 2.1.0
